services:
  nginx:
    container_name: nginx
    image: docker.io/library/nginx:alpine
    restart: unless-stopped
    command: ["/bin/sh", "/generate_htpasswd.sh"]
    env_file:
      - .env
    networks:
      - searxng
    ports:
      - "443:443"
    volumes:
      - ./example_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./key.pem:/etc/nginx/ssl/key.pem:ro
      - ./generate_htpasswd.sh:/generate_htpasswd.sh:ro
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    #ports:
    #  - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  valkey-data2:
  searxng-data:
